version: '2'
services:
  config-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: fisi1017/config-service
    restart: always
    ports:
      - 8888:8888
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  oauth2-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: fisi1017/oauth2-service
    restart: always
    ports:
      - 5000:5000
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  auth-mongodb:
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: fisi1017/oauth2-service-mongodb
    restart: always
    ports:
      - 25000:27017
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  discovery-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: fisi1017/discovery-service
    restart: always
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  api-gateway-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: fisi1017/api-gateway-service
    restart: always
    ports:
      - 4000:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  hystrix-dashboard:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: fisi1017/hystrix-dashboard
    restart: always
    ports:
      - 9000:9000
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  turbine-server:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: fisi1017/turbine-server
    restart: always
    ports:
      - 8989:8989
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
    logging:
      options:
        max-size: "10m"
        max-file: "10"