version: '2'
services:
  mysqldb:
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: webshop
      MYSQL_USER: shop
      MYSQL_PASSWORD: shop
    image: mysql
    restart: always
    ports:
    - 3307:3306
    logging:
      options:
        max-size: 10m
        max-file: '10'
  discovery-service:
    image: mefiroofficial/discovery-service
    restart: always
    ports:
    - 8761:8761
    logging:
      options:
        max-size: 10m
        max-file: '10'
  api-gateway-service:
    image: mefiroofficial/api-gateway-service
    restart: always
    ports:
    - 4000:4000
    logging:
      options:
        max-size: 10m
        max-file: '10'
  user-core-service:
    image: mefiroofficial/user-core-service
    restart: always
    ports:
    - 9876:9876
    logging:
      options:
        max-size: 10m
        max-file: '10'
#  user-core-service2:
##    environment:
##      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
#    image: mefiroofficial/user-core-service
#    restart: always
#    ports:
#    - 9877:9876
#    logging:
#      options:
#        max-size: 10m
#        max-file: '10'
  user-composite-service:
    image: mefiroofficial/user-composite-service
    restart: always
    ports:
    - 10000:10000
    logging:
      options:
        max-size: 10m
        max-file: '10'
  product-core-service:
    image: mefiroofficial/product-core-service
    restart: always
    ports:
    - 10100:10100
    logging:
      options:
        max-size: 10m
        max-file: '10'
  category-core-service:
    image: mefiroofficial/category-core-service
    restart: always
    ports:
    - 10200:10200
    logging:
      options:
        max-size: 10m
        max-file: '10'
  role-core-service:
    image: mefiroofficial/role-core-service
    restart: always
    ports:
    - 10400:10400
    logging:
      options:
        max-size: 10m
        max-file: '10'
  product-category-composite-service:
    image: mefiroofficial/product-category-composite-service
    restart: always
    ports:
    - 10300:10300
    logging:
      options:
        max-size: 10m
        max-file: '10'
  webshop-ui:
    image: mefiroofficial/webshop-ui
    restart: always
    ports:
    - 80:80
    logging:
      options:
        max-size: 10m
        max-file: '10'